---
- name: install postgres and python dependencies
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: install python dependency
  pip: name=psycopg2 state=present

- name: create pg user
  postgresql_user: name=railsappuser password=railsapppassword db=railsappdb priv=ALL
