---
- name: configure redis in application.rb
  lineinfile:
    dest: /vagrant/webapp/config/application.rb
    insertafter: "Rails::Application"
    line: "config.cache_store = :redis_store, ENV['CACHE_URL']"

- name: replace sqlite3 by postgres in Gemfile
  lineinfile: dest=/vagrant/webapp/Gemfile regexp="^gem 'sqlite3'" line="gem 'pg'"

- name: add gems to Gemfile
  blockinfile:
    dest: /vagrant/webapp/Gemfile
    block: |
      group :development, :test do
        gem 'rspec-rails', '~> 3.4'
      end

      gem 'sinatra', require: false
      gem 'slim'
      gem 'puma'
      gem 'pry-rails', :group => :development
      gem 'factory_girl_rails'
      gem 'redis-rails', '~> 4.0.0'
      gem 'sidekiq'

- name: copy sidekiq initializer
  copy: src=sidekiq.rb dest=/vagrant/webapp/config/initializers/sidekiq.rb

- name: copy puma config to app
  copy: src=puma.rb dest=/vagrant/webapp/config/puma.rb

- name: copy database.yml file
  copy: src=database.yml dest=/vagrant/webapp/config/database.yml

- name: copy dot env file
  copy: src=.rails-app.env dest=/vagrant/webapp/.rails-app.env

- name: require sidekiq web to routes
  lineinfile: dest=/vagrant/webapp/config/routes.rb line="require 'sidekiq/web'" insertbefore=BOF

- name: mount sidekiq web in rails app
  lineinfile: dest=/vagrant/webapp/config/routes.rb line="mount Sidekiq::Web, :at => '/sidekiq'" insertafter="Rails.application.routes.draw do"
