---
- hosts: all
  become: yes
  roles:
    - { role: setup, tags: ['setup'] }
    
    - { role: bootstrap-new-rails-app, tags: ['new-rails-app', 'bootstrap'] }
    - { role: webserver, tags: ['webserver', 'bootstrap'] }
    - { role: app-server, tags: ['app-server', 'bootstrap'] }
    - { role: database, tags: ['database', 'bootstrap'] }
    - { role: cache-store, tags: ['cache-store', 'bootstrap'] }
    - { role: background-job, tags: ['background-job', 'bootstrap'] }
    - { role: dockerize-rails-app, tags: ['dockerize', 'bootstrap'] }
