---
- name: move Dockerfile to remote host
  template: src=Dockerfile.j2 dest={{ vm_shared_folder }}/{{ app_folder }}/Dockerfile

- name: move docker-compose.yml to remote host
  template: src=docker-compose.yml.j2 dest={{ vm_shared_folder }}/{{ app_folder }}/docker-compose.yml
