---
- name: move Dockerfile to remote host
  template: src=Dockerfile.j2 dest=/vagrant/webapp/Dockerfile

- name: move docker-compose.yml to remote host
  template: src=docker-compose.yml.j2 dest=/vagrant/webapp/docker-compose.yml
